FROM node:18

WORKDIR /app

# Copy only package files first for faster builds
COPY package.json package-lock.json ./
RUN npm install

# Copy rest of the app
COPY . .

# Install nodemon globally for auto-reloading
RUN npm install -g nodemon

# Start in development mode
CMD ["npm", "run", "dev"]

EXPOSE 5000
